### ISSUE TITLE
gzipped file input

### ISSUE THREAD

**Issue by inutano** [suecharo/tataki#1]
and other common compression methods

**Comment by fmaccha** [comment]
I think there are some points to consider how we want to implement this.


1. Whether to add the option, e.g. `--decode`, to explicitly instruct `tataki` to decompress the input file.

By adding the option, users can choose whether to decode the input file. 

2. Assuming we are decompressing the input file, how do we indicate the output result shows the result after decompression.

I've thought of two ways to do this, we could add a new entry in the output with 'decoded' added to its suffix.

```
foo.fastq.gz_decoded:
  label: FASTQ
  id: http://edamontology.org/format_1930
```

Or, add an element `decoded` indicates that it has been decompressed.

```
foo.fastq.gz:
  label: FASTQ
  id: http://edamontology.org/format_1930
  decoded: gzip
```

3. Assuming we are decompressing the input file, do we display both the results before and after the decompression.

This involves with the second point. If we are to show the both compressed and decompressed results and choose to add 'decoded' to the result of decompressed one, the output look like this.

```
foo.fastq.gz:
  label: GZIP format
  id: http://edamontology.org/format_3989
foo.fastq.gz_decoded:
  label: FASTQ
  id: http://edamontology.org/format_1930
```

4. Assuming we are NOT decompressing the file, some compression and archive formats are not supported by EDAM.

Gzip is suppported so its result looks like this below, 

```
foo.fastq.gz:
  label: GZIP format
  id: http://edamontology.org/format_3989
```

but the problem is that how do we treat formats like Bzip2?

```
foo.fastq.bz2:
  label: ?
  id: ?
```

**Comment by fmaccha** [comment]
design memo

- try to decompress input files by default
- add an `--no-decompress` option and do not decompress the files if specified.
- store the decompressed content to a temporary file
    - if `--tidy`, then decompress all lines
    - if no `--tidy` option, then decompress `--num-records * 4 + max(20, (number of lines starting with '#' or '@')` lines
        - conflict with cwl extension mode and terminate the run with an error
- do not decompress if an input is in BGZF format (i.e. VCF, BCF, BAM)
- add a new key-value pair with the key named "decompressed"

ex.

```
$ ./tataki foo.fastq.gz

foo.fastq.gz:
  label: FASTQ
  id: http://edamontology.org/format_1930
  decompressed: GZIP
```

```
$ ./tataki foo.fastq.gz --no-decompress

foo.fastq.gz:
  label: GZIP format
  id: http://edamontology.org/format_3989
  decompressed: null
```

**Comment by inutano** [comment]
The field name `decompressed` sounds as if it shows the file was decompressed or not with a boolean value. If we wanted to show the compression format and the format of the compressed file explicitly, then the data should look like:

```
foo.fastq.gz:
  label: GZIP format
  id: http://edamontology.org/format_3989
  decompressed:
    label: FASTQ
    id: http://edamontology.org/format_1930
```

wdyt @fmaccha ?

**Comment by fmaccha** [comment]
I agree with it. That way the information is more explicit and also maintains backward compatibility with the current one.

I did consider putting the label and id of the compression format on a dedicated level like the example below. It could be easier in the future to add more entities to both the compressed and decompressed sections, but I don't foresee us needing to add more stuff and complicate things anyway. No backward compatibility as well.

```yaml
# not good
foo.fastq.gz:
  compressed:
    label: GZIP format
    id: http://edamontology.org/format_3989
  decompressed:
    label: FASTQ
    id: http://edamontology.org/format_1930
```

One thing to keep in mind is that Edam does not support all compression formats, so we might have to use `null` for id and label like we do for those file formats not supported by tataki.
Perhaps we could PR to EDAM.

```yaml
# might have to use null for bz2
foo.fastq.bz2:
  label: null
  id: null
  decompressed:
    label: FASTQ
    id: http://edamontology.org/format_1930
```
