### ISSUE TITLE
Chimera files which start with FASTA and then other formats are incorrectly detected as FASTA

### ISSUE THREAD

**Issue by fmaccha** [suecharo/tataki#7]
Files that have FASTA format followed by other formats, like show below, are incorrectly detected as FASTA.

```
>ref
AGCATGTTAGATAAGATAGCTGTGCTAGTAGGCAGTCAGCGCCAT
>ref2
aggttttataaaacaattaagtctacagagcaactacgcg
@HD     VN:1.0 SO:coordinate
```

```
./chimera.txt:
  decompressed:
    id: null
    label: null
  label: FASTA
  id: http://edamontology.org/format_1929
```

This happened because `noodles::fasta` read the sam header line at the end as FASTA sequence. [Its documentation](https://docs.rs/noodles/latest/noodles/fasta/index.html) says, 

> FASTA is a text format with no formal specification and only has de facto rules. It typically consists of a list of records, each with a definition on the first line and a sequence in the following lines.
